version: "3.8"
services:
    api:
        container_name: physical-computing-api
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "7001:7001"
        volumes:
            - ./src:/app/src
        restart: unless-stopped
